### ISSUE TITLE
An error occurred in line <1983> for nucleationModel_preferential, dendriticSolidification, and other applications

### ISSUE THREAD

**Issue by GabroxylicAcid** [prisms-center/phaseField#159] opened 2020-06-14 22:49 UTC
Hi! I'm new to this. 
After `running mpirun -n 1 main`
This is what I get:

```
An error occurred in line <1983> of file <../source/base/parameter_handler.cc> in function
    void dealii::ParameterHandler::scan_line(std::__cxx11::string, const string&, unsigned int)
The violated condition was: 
    entries->get_child_optional (get_current_full_path(subsection))
Additional information: 
    Line <44> of file <parameters.in: There is no such subsection to be entered: Refinement criterion: n
--------------------------------------------------------

Aborting!
----------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[42277,1],0]
  Exit code:    1

```

What could be the problem?

**Comment by david-montiel-t** [comment] 2020-06-14 23:13
Hello,

It looks like there is an issue in the mesh refinement settings.

Did you modified any of the files of the preferentialNucleation
application?

If you did, can you send me the file(s) you modified?

David

**Comment by GabroxylicAcid** [comment] 2020-06-15 16:09
Hello,

I have not modified anything as I'm trying to run the example applications first. Although, I was able to run cahnHilliard only.

Thanks.

Gab

**Comment by david-montiel-t** [comment] 2020-06-15 17:06
Hello Gab,

I found an issue with the compilation of the nucleationModel_preferential
application. I will work on fixing it and let you know when it is ready.

However, the dendriticSolidification (and other) applications work fine in
my local installation. Can you let me know if you have the traditional
installation or the Docker installation? Also have you made sure to
download the most updated version of PRISMS-PF?

Thank you,

David

**Comment by GabroxylicAcid** [comment] 2020-06-15 17:10
Hello David,

Thank you. 

As for the dendriticSolidification, I have installed from Docker. I just learned of the PRISMS-PF two days ago and it seemed promising so I tried installing it. I had no issue in installing CMake, however, I had trouble installing deal.ii binary package as there was an issue with 9.2.0 in Mac OSX 10.14. So I tried installing from Docker same with PRISMS-PF. 

Thank you!

Gab

**Comment by david-montiel-t** [comment] 2020-06-15 19:02
Hello Gab,

I think the issue is that the Docker container is slightly out of date. And
when you bind to the host volume, you combine the outdated core library
(from the Docker container) with the applications written for the new
version of PRISMS-PF, which you have just cloned from the github
repository, so there is a conflict.

I suggest that you try the following steps. Assuming that you cloned the
PRISMS-PF repository inside the folder ~/DockerWorkspace, launch the docker
environment using the following line:

*$ docker run -ti -v
~/DockerWorkspace/phaseField:/home/dealii/phaseField stvdwtt/prismspf:prismspf*

Then inside PRISMS-PF Docker environment, go to the folder *phaseField *and
compile the core library
$ cmake .
$ make -j 8

It may take a while (about 5 mins.) but after that you'll be using the most
up-to-date version of PRISMS-PF. Then go to any application and re-compile
(but first delete the file CMakeCache.txt if there is one)
$ rm CMakeCache.txt
$ cmake .
$ make -j 8

Finally, run your code:

$ mpirun -n 1 main

This should work because you will be using the latest version of both the
core library and the applications.

Hope this helps. Let me know if you still have issues. The new Docker
installation will be released very soon.

David

**Comment by GabroxylicAcid** [comment] 2020-06-15 19:40
Hello David,

Thank you for the response.
I still get the same error. I tried your suggestion above:

`Gabs-MacBook-Air:~ GabroxylicAcid$ docker run -ti -v ~/DockerWorkspace/phaseField/applications:/home/dealii/phaseField/applications stvdwtt/prismspf:prismspf
dealii@716fbb19bc30:~/phaseField$ cmake .
-- Using the deal.II-9.0.0 installation found at /home/dealii/dealii-v9.0.0
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_initialize_cached_variables.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_query_git_information.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_setup_target.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_invoke_autopilot.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_add_test.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dealii/phaseField
dealii@716fbb19bc30:~/phaseField$ make -j 8
[  2%] Linking CXX static library libprisms_pf.a
[  2%] Linking CXX static library libprisms_pf_debug.a
[ 51%] Built target prisms_pf
[100%] Built target prisms_pf_debug
dealii@716fbb19bc30:~/phaseField$ rm CMakeCache.txt
dealii@716fbb19bc30:~/phaseField$ cmake .
-- Using the deal.II-9.0.0 installation found at /home/dealii/dealii-v9.0.0
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_initialize_cached_variables.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_query_git_information.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_setup_target.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_invoke_autopilot.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_add_test.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dealii/phaseField
dealii@716fbb19bc30:~/phaseField$ make -j 8
Scanning dependencies of target prisms_pf
Scanning dependencies of target prisms_pf_debug
[ 50%] Built target prisms_pf_debug
[100%] Built target prisms_pf
dealii@716fbb19bc30:~/phaseField$ cd applications/dendriticSolidification/
dealii@716fbb19bc30:~/phaseField/applications/dendriticSolidification$ cmake .
-- Using the deal.II-9.0.0 installation found at /home/dealii/dealii-v9.0.0
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_initialize_cached_variables.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_query_git_information.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_setup_target.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_invoke_autopilot.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_add_test.cmake
-- Using the deal.II-9.0.0 installation found at /home/dealii/dealii-v9.0.0
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_initialize_cached_variables.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_query_git_information.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_setup_target.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_invoke_autopilot.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_add_test.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dealii/phaseField
[ 50%] Built target prisms_pf_debug
[100%] Built target prisms_pf
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dealii/phaseField/applications/dendriticSolidification
dealii@716fbb19bc30:~/phaseField/applications/dendriticSolidification$ make debug
[100%] Switch CMAKE_BUILD_TYPE to Debug
-- Using the deal.II-9.0.0 installation found at /home/dealii/dealii-v9.0.0
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_initialize_cached_variables.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_query_git_information.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_setup_target.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_invoke_autopilot.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_add_test.cmake
-- Using the deal.II-9.0.0 installation found at /home/dealii/dealii-v9.0.0
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_initialize_cached_variables.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_query_git_information.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_setup_target.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_invoke_autopilot.cmake
-- Include macro /home/dealii/dealii-v9.0.0/share/deal.II/macros/macro_deal_ii_add_test.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dealii/phaseField
make[4]: Entering directory '/home/dealii/phaseField'
make[5]: Entering directory '/home/dealii/phaseField'
make[6]: Entering directory '/home/dealii/phaseField'
make[6]: Leaving directory '/home/dealii/phaseField'
[ 50%] Built target prisms_pf_debug
make[6]: Entering directory '/home/dealii/phaseField'
make[6]: Leaving directory '/home/dealii/phaseField'
[100%] Built target prisms_pf
make[5]: Leaving directory '/home/dealii/phaseField'
make[4]: Leaving directory '/home/dealii/phaseField'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dealii/phaseField/applications/dendriticSolidification
[ 50%] Linking CXX executable main
[100%] Built target main
Built target debug
dealii@716fbb19bc30:~/phaseField/applications/dendriticSolidification$ mpirun -n 1 main
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/X7MHTOP4KJ3Y7NKIYFZNWZGEKT:/var/lib/docker/overlay2/l/EIRFTDCJMYSH2GGLUMGOI7BKRG:/var/lib/docker/overlay2/l/B6TV6NHB4PHOIA3NTXBTVBIMLW:/var/lib/docker/overlay2/l/JZ22WAZX3VN7ZC2QX5DW6SF3UM:/var/lib/docker/overlay2/l/22J6TOEYGANN2MOOJLKC7C2JM2:/var/lib/docker/overlay2/l/TCO73GWMQKJDMGUAJH5QLZUG5P:/var/lib/docker/overlay2/l/UFGDJGM6QC3RTXT3RDYOWVHTQY:/var/lib/docker/overlay2/l/OA6EFXTUCC4OT66GBOQU7M54SM:/var/lib/docker/overlay2/l/GBFIURZF4VMDC'
Unexpected end of /proc/mounts line `QZDCRRORWEPQ3:/var/lib/docker/overlay2/l/HJ4S5JL6AQX5JBA2JVNO63FJMN:/var/lib/docker/overlay2/l/ZOYKFJWSMRVK7BUP55C6JUUNFV:/var/lib/docker/overlay2/l/FG3CPKWCL7FHPIHYQCRP7HBPGB:/var/lib/docker/overlay2/l/544DMBTVGX7DFBUHGRWJU6ICWU:/var/lib/docker/overlay2/l/ITXJYCV7VDGOBOCFNA7NPALCVM:/var/lib/docker/overlay2/l/W7LBW5YVVQNZWHZ7NHHPCJR3BR:/var/lib/docker/overlay2/l/U6JZBW75VO4PTOOH3SOLAVD4PJ:/var/lib/docker/overlay2/l/QOK6QPYOU6WM3HP6NHU27FDBBS:/var/lib/docker/overlay2/l/DYN5CVYETGYVWX4JAZ2J4C7H5A:/var/lib/do'
Using the input parameter file: parameters.in
Number of constants: 6
Number of post-processing variables: 0


----------------------------------------------------
PRISMS-PF: Exception on processing: 

--------------------------------------------------------
An error occurred in line <1983> of file <../source/base/parameter_handler.cc> in function
    void dealii::ParameterHandler::scan_line(std::__cxx11::string, const string&, unsigned int)
The violated condition was: 
    entries->get_child_optional (get_current_full_path(subsection))
Additional information: 
    Line <47> of file <parameters.in: There is no such subsection to be entered: Refinement criterion: phi
--------------------------------------------------------

Aborting!
----------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10027,1],0]
  Exit code:    1
--------------------------------------------------------------------------
dealii@716fbb19bc30:~/phaseField/applications/dendriticSolidification$ 
`
Thank you.

Gab

**Comment by GabroxylicAcid** [comment] 2020-06-15 19:53
Hello David,

Is it an issue that I am still using deal.ii 9.0.0? or do I have to install the 9.2.0?

Thanks.

Gab

**Comment by david-montiel-t** [comment] 2020-06-15 19:53
Hello Gab,

Looks like you wrote the following line:

docker run -ti -v
~/DockerWorkspace/phaseField/applications:/home/dealii/phaseField/applications
stvdwtt/prismspf:prismspf

However, the line I suggested doesn't include "applications":

*$ docker run -ti -v
~/DockerWorkspace/phaseField:/home/dealii/phaseField stvdwtt/prismspf:prismsp*

Can you try again?

David

**Comment by david-montiel-t** [comment] 2020-06-15 19:55
The version of deal.ii should not be an issue. Please refer my last email.

**Comment by GabroxylicAcid** [comment] 2020-06-15 20:13
Hello David,

Thank you for pointing it out. I am currently trying it. 
However, after 
`make -j 8 `
I have been encountering error like
```[ 10%] Building CXX object CMakeFiles/prisms_pf.dir/src/matrixfree/utilities.cc.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/prisms_pf_debug.dir/build.make:206: recipe for target 'CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeLHS.cc.o' failed
make[2]: *** [CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeLHS.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....
```

It is still currently running. Is this something that I should be worried about? What could have went wrong?

Thanks.

Gab

**Comment by david-montiel-t** [comment] 2020-06-15 20:39
Can you cancel the compilation and try with just  "make" (without the "-j
8")?

Like this:

$ make

That worked for me.

David

**Comment by GabroxylicAcid** [comment] 2020-06-15 21:34
It did not work.

```
dealii@c80f3f91c95d:~/phaseField/applications/dendriticSolidification$ mpirun -n 1 main
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/IFK4P3L3MJUXHSNHQX47WKTXUQ:/var/lib/docker/overlay2/l/EIRFTDCJMYSH2GGLUMGOI7BKRG:/var/lib/docker/overlay2/l/B6TV6NHB4PHOIA3NTXBTVBIMLW:/var/lib/docker/overlay2/l/JZ22WAZX3VN7ZC2QX5DW6SF3UM:/var/lib/docker/overlay2/l/22J6TOEYGANN2MOOJLKC7C2JM2:/var/lib/docker/overlay2/l/TCO73GWMQKJDMGUAJH5QLZUG5P:/var/lib/docker/overlay2/l/UFGDJGM6QC3RTXT3RDYOWVHTQY:/var/lib/docker/overlay2/l/OA6EFXTUCC4OT66GBOQU7M54SM:/var/lib/docker/overlay2/l/GBFIURZF4VMDC'
Unexpected end of /proc/mounts line `QZDCRRORWEPQ3:/var/lib/docker/overlay2/l/HJ4S5JL6AQX5JBA2JVNO63FJMN:/var/lib/docker/overlay2/l/ZOYKFJWSMRVK7BUP55C6JUUNFV:/var/lib/docker/overlay2/l/FG3CPKWCL7FHPIHYQCRP7HBPGB:/var/lib/docker/overlay2/l/544DMBTVGX7DFBUHGRWJU6ICWU:/var/lib/docker/overlay2/l/ITXJYCV7VDGOBOCFNA7NPALCVM:/var/lib/docker/overlay2/l/W7LBW5YVVQNZWHZ7NHHPCJR3BR:/var/lib/docker/overlay2/l/U6JZBW75VO4PTOOH3SOLAVD4PJ:/var/lib/docker/overlay2/l/QOK6QPYOU6WM3HP6NHU27FDBBS:/var/lib/docker/overlay2/l/DYN5CVYETGYVWX4JAZ2J4C7H5A:/var/lib/do'
Using the input parameter file: parameters.in
Number of constants: 6
Number of post-processing variables: 0
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 945 on node c80f3f91c95d exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
dealii@c80f3f91c95d:~/phaseField/applications/dendriticSolidification$ 
```
Maybe I had to install everything again. 

Gab

**Comment by david-montiel-t** [comment] 2020-06-15 21:41
Yes, sorry. Could you start again followimg the procedure I described in my
long email?

Make sure you delete the files CMakeCache.txt (if existing) before you do

$cmake .

both in the core library (phaseField) and the application directory.

Also type "make" to compile instead of "make -j 8"

David

**Comment by david-montiel-t** [comment] 2020-06-15 21:42
Also, since you have not made any changes, you can also re-clone the
repository.

**Comment by GabroxylicAcid** [comment] 2020-06-15 22:09
Hello David,

Will try to do this again later. I will update you about this.

Moreover, would it be alright if I reach out to you via email about some clarifications about example applications and creating customs apps soon? 

Thank you.

Gab

**Comment by david-montiel-t** [comment] 2020-06-15 23:24
Yes, of course.

Though I would encourage you to send it to *prisms-pf-users@googlegroups.com
<prisms-pf-users@googlegroups.com> *so other people have access to the
conversation, which might contain useful information for them.

Best,

David

**Comment by david-montiel-t** [comment] 2020-06-15 23:25
Also, if you are not a member yet and want to join the prisms-pf user
group, please fill out the following registration link:

https://docs.google.com/forms/d/e/1FAIpQLSdeEKqHC6R-2YUnHNd0QQBIlYTs2mbr5qQfhpmjKvG70id7kQ/viewform?c=0&w=1

**Closed** 2021-07-22 02:48 UTC
